# Generated by Django 4.1.5 on 2023-05-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_person_email_person_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='joined_date',
            field=models.DateField(null=True),
        ),
    ]
